import { FaWineGlassEmpty } from "react-icons/fa6";
import supplierModel from "../models/supplierModel.js";
import asyncHandler from "express-async-handler";

// Get
const getAllSupplier = asyncHandler(async (req, res) => {
  try {
    const suppliers = await supplierModel
      .find()
      .populate("materialSupplied")
      .sort({ orderDate: -1 });
    // .populate('materialsSupplied');
    res.json(suppliers);
  } catch (error) {
    res.status(500).json({ error: err.message });
  }
});

const getSupplierById = asyncHandler(async (req, res) => {
  try {
    const supplier = await supplierModel.findById(req.params.id);
    // .populate('materialsSupplied');
    if (!supplier) {
      return res.status(400).json({ errors: "Supplier not found" });
    }
    res.status(200).json(supplier);
  } catch (error) {
    res.status(500).json({ error: err.message });
  }
});

// Create
const createSupplier = asyncHandler(async (req, res) => {
  const {
    supplierName,
    // supplierCode,
    contactPerson,
    contactEmail,
    contactPhone,
    // New
    // address,
    street,
    city,
    state,
    zipCode,
    country,
    paymentTerms,
    materialSupplied,
    rating,
    email,
    password,
    supplierType,
    // materialsSupplied,
  } = req.body;

  const newSupplier = new supplierModel({
    supplierName: supplierName,
    // supplierCode: supplierCode,
    contactPerson: contactPerson,
    contactEmail: contactEmail,
    contactPhone: contactPhone,
    address: {
      street,
      city,
      state,
      zipCode,
      country,
    },

    paymentTerms: paymentTerms,
    rating: rating,
    materialSupplied: materialSupplied,
    email: email,
    password: password,
    supplierType: supplierType,
  });

  try {
    const saveSuppliers = await newSupplier.save();
    res.status(201).json(saveSuppliers);
  } catch (err) {
    res.status(400).json({ errors: err.message });
  }
});

// Update
const updateSupplier = asyncHandler(async (req, res) => {
  const {
    supplierName,
    contactPerson,
    contactEmail,
    contactPhone,
    address,
    paymentTerms,
    rating,
    materialsSupplied,
  } = req.body;

  try {
    const updatedSupplier = await newSupplier.findByIdAndUpdate(
      req.parms.id,
      {
        supplierName,
        contactPerson,
        contactEmail,
        contactPhone,
        address,
        paymentTerms,
        rating,
        materialsSupplied,
      },
      true
    );

    if (!updatedSupplier)
      return res.status(404).json({ errors: "Supplier not found" });

    res.json(updatedSupplier);
  } catch (error) {
    res.status(400).json({ error: error.messages });
  }
});

// Supplier Delete
const deleteSupplier = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const supplier = await supplierModel.findByIdAndDelete(id);

  if (!supplier) {
    return res
      .status(400)
      .json({ success: false, message: "Supplier Not Found" });
  }

  res
    .status(200)
    .json({ success: true, message: `"Deleted Successfully!"${id}` });
});

// COMPLETE Registration
// COMPLETE Registration
const completeRegistration = asyncHandler(async (req, res) => {
  const {
    email, // Include email for finding the supplier
    supplierName,
    contactPerson,
    contactEmail,
    contactPhone,
    street,
    city,
    state,
    zipCode,
    country,
    paymentTerms,
  } = req.body;

  // Ensure required fields are provided
  if (
    !email ||
    !supplierName ||
    !contactPerson ||
    !contactEmail ||
    !contactPhone ||
    !street ||
    !city ||
    !state ||
    !zipCode ||
    !country ||
    !paymentTerms
  ) {
    return res.status(400).json({ error: "All fields are required." });
  }

  // Find the supplier by email
  const supplier = await supplierModel.findOne({ email });

  if (!supplier) {
    return res.status(404).json({ error: "Supplier not found." });
  }

  if (supplier.status !== "Pending") {
    return res
      .status(400)
      .json({ error: "Supplier account is not pending verification." });
  }

  // Prepare the data to update
  const updatedData = {
    supplierName,
    contactPerson,
    contactEmail,
    contactPhone,
    address: {
      street,
      city,
      state,
      zipCode,
      country,
    },
    paymentTerms,
  };

  // Update supplier details and activate the account
  Object.assign(supplier, updatedData, { status: "Active" });

  // Save the updated supplier (supplierCode will be generated by pre-save hook)
  await supplier.save();

  res.status(200).json({
    message: "Supplier details updated successfully and account activated.",
    supplier,
  });
});

export {
  getAllSupplier,
  getSupplierById,
  createSupplier,
  updateSupplier,
  deleteSupplier,
  completeRegistration,
};
